name: deploy
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: '${{ steps.deploy-to-github-pages.outputs.url }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install .Net Wasm Tools
        run: dotnet workload install wasm-tools
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish .Net
        run: >-
          dotnet publish BlazorDeploy.csproj -c:Release -o docs --no-logo
          ./publish
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload
        uses: actions/upload-pages-artifact@v3
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
